networks:
  piwigo-network:
    external: false

services:
  piwigo-backend:
    image: docker.io/rushlana/piwigo-test:latest
    networks:
      - piwigo-network
    ports:
      - '${piwigo_port}:80'
    depends_on:
      - piwigo-db
    volumes:
      - ./piwigo-data/_data:/var/www/html/piwigo/_data
      - ./piwigo-data/upload:/var/www/html/piwigo/upload
      - ./piwigo-data/galleries:/var/www/html/piwigo/galleries
      - ./piwigo-data/config:/var/www/html/piwigo/local/config
  piwigo-db:
    image: docker.io/mariadb:lts
    restart: always
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=true
      # Defined in .env
      - MARIADB_USER=${db_user}
      - MARIADB_PASSWORD=${db_user_password}
      - MARIADB_DATABASE=${db_name}
    networks:
      - piwigo-network
    volumes:
      - ./piwigo-data/mysql:/var/lib/mysql