networks:
  piwigo-network:
    external: false

services:
  piwigo-backend:
    image: ghcr.io/piwigo/piwigo:latest
    networks:
      - piwigo-network
    ports:
      - '${piwigo_port}:80'
    volumes:
      - ./piwigo-data/piwigo:/var/www/html/piwigo/
      - ./piwigo-data/scripts:/usr/local/bin/scripts/