#!/command/with-contenv sh
set -eu
TZVAL="${TZ:-Europe/Paris}"
PHPV="${PHP_VERSION:-84}"

# check if we found the timezone in /usr/share/zoneinfo
if [ ! -e "/usr/share/zoneinfo/${TZVAL}" ]; then
  echo "[timezone] '${TZVAL}' not found, fallback UTC" >&2
  TZVAL="UTC"
fi

# for nginx/cron/log etc..
ln -snf "/usr/share/zoneinfo/$TZVAL" /etc/localtime
echo "$TZVAL" > /etc/timezone
# for php-fpm
echo "date.timezone=${TZVAL}" > "/etc/php${PHPV}/conf.d/99-timezone.ini"

echo "[timezone] set to '${TZVAL}'" >&2
